version: "3.8"

services:
  redis:
    image: redis:alpine
    restart: always
  web:
    build: ./R4C
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./R4C/:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
  worker:
    restart: always
    build:
      context: ./R4C/
    volumes:
      - ./R4C/:/code
    command: celery -A R4C worker --loglevel=info
    depends_on:
      - redis
      - web
    env_file:
      - .env
  beat:
    restart: always
    build:
      context: ./R4C/
    volumes:
      - ./R4C/:/code
    command: celery -A R4C beat --loglevel=info
    depends_on:
      - redis
      - web
    env_file:
      - .env
